---
title: "rdwd"
author: "Berry Boessenkool, <berry-b@gmx.de>"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
editor_options: 
  chunk_output_type: console
---

# Intro
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/)

# Package structure
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/package-structure.html)

# Interactive map
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/interactive-map.html)

# Available datasets
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/available-datasets.html)

# Station selection
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/station-selection.html)

# fileIndex
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/fileindex.html)

# fread
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/fread.html)

# Raster data
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/raster-data.html)

# see also
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/see-also.html)

# - use case: recent time series
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-recent-time-series.html)

# - use case: long term climate graph
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-long-term-climate-graph.html)

# - use case: merge historical and recent data
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-merge-historical-and-recent-data.html)

# - use case: vectorized data
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-vectorized-data.html)

# - use case: monthy gridded data
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-monthy-gridded-data.html)

# - use case: values at locations in grid
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-values-at-locations-in-grid.html)

# - use case: daily radar files
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-daily-radar-files.html)

# - use case: recent hourly radar files
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-recent-hourly-radar-files.html)

# - use case: longest time series in Berlin
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-longest-time-series-in-berlin.html)

# - use case: Rainfall intensity depends on temperature
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-rainfall-intensity-depends-on-temperature.html)

# - use case: Get all daily rainfall data 2014:2016
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-get-all-daily-rainfall-data-20142016.html)

# - use case: plot all rainfall values around a given point
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-plot-all-rainfall-values-around-a-given-point.html)

# - use case: map climate data to Landkreise
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-map-climate-data-to-landkreise.html)

# - use case: phenology data
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-phenology-data.html)

# - use case: derived data
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/use-case-derived-data.html)

# history
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/history.html)

# search
This website has been moved to [brry.github.io/rdwd](https://brry.github.io/rdwd/search.html)
